### ISSUE TITLE
[Hope]: 请求移除聊天界面的等级显示

### ISSUE THREAD

**Issue by Dreamry2C** [LiteLoaderQQNT/LiteLoaderQQNT#285]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

![QQ截图20240505202925](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/58101503/e7cdd523-6c4e-404c-bf21-2c8c99545b38)

如图，新版QQ会在群聊中会显示聊天等级，尽管已经很淡了但仍然想要去除（有个问题，群主管理员和等级是连在一起的，希望只是去除等级）

**Comment by xinyihl** [comment]
使用 [transitio](https://github.com/PRO-2684/transitio) 加载这个 css 片段
``` css
.ml-item span{
    &.level{
        display: none !important;
    }
    & + &.title{
        margin-left: unset !important;
    }
}
```
